import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Snagged",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        <main className="flex min-h-svh flex-col items-center justify-center bg-gradient-to-b from-[#ffffff] to-orange-100/50">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
